EducacionAvanzada/educacionavanzada-master/Educacion Avanzada/educacionRespaldo-master/EducacionAvanzada/EducacionAvanzada.Web/Controllers/AlumnosController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.Web.Controllers
{
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {
            var alumnosBL = new AlumnosBL();
            var listaAlumno = alumnosBL.ObtenerAlumnos();

            return View(listaAlumno);
        }
    }
}

EducacionAvanzada/educacionavanzada-master/Educacion Avanzada/educacionRespaldo-master/EducacionAvanzada/EducacionAvanzada.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

EducacionAvanzada/educacionavanzada-master/Educacion Avanzada/educacionRespaldo-master/EducacionAvanzada/EducacionAvanzada.Web/Views/Alumnos/Index.cshtml
@model List<EducacionAvanzada.BL.Alumno>
@{
    ViewBag.Title = "Index";
}

<h2>Alumnos</h2>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Codigo
            </th>
            <th>
                Nombre
            </th>
            <th>
                Jornada
            </th>
            <th>
                Grado
            </th>
            <th>
                Seccion
            </th>
        </tr>
    </thead>

    @foreach (var alumno in Model)
    {
        <tr>
            <td>@alumno.Id</td>
            <td>@alumno.Nombre</td>
            <td>@alumno.Jornada</td>
            <td>@alumno.Grado</td>
            <td>@alumno.Seccion</td>
        </tr>
    }
</table>

EducacionAvanzada/educacionavanzada-master/Educacion Avanzada/educacionRespaldo-master/EducacionAvanzada/EducacionAvanzada.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>BIENVENIDOS A EDUCACION AVANZADA</h2>

EducacionAvanzada/educacionavanzada-master/Educacion Avanzada/educacionRespaldo-master/EducacionAvanzada/EducacionAvanzada.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Educación Avanzada", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Lista de Alumnos", "Index", "Alumnos")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>